### ISSUE TITLE
segfault during copy into foreign table

### ISSUE THREAD

**Issue by fjalvingh** [citusdata/cstore_fdw#237]
I made a core dump; the backtrace is:

#0  0x0000555d6dd6d128 in CheckExprStillValid ()
#1  0x0000555d6dd6d230 in ExecInterpExprStillValid ()
#2  0x0000555d6dd0a54d in NextCopyFrom ()
#3  0x00007fa636521871 in CopyIntoCStoreTable (queryString=<optimized out>, copyStatement=<optimized out>) at cstore_fdw.c:594
#4  CStoreProcessCopyCommand (completionTag=0x7ffd48351980 "", queryString=<optimized out>, copyStatement=<optimized out>) at cstore_fdw.c:493
#5  CStoreProcessUtility (plannedStatement=<optimized out>, queryString=<optimized out>, context=<optimized out>, paramListInfo=<optimized out>, 
    queryEnvironment=0x0, destReceiver=0x555d7016b9c0, completionTag=0x7ffd48351980 "") at cstore_fdw.c:293
#6  0x0000555d6ded0d14 in ?? ()
#7  0x0000555d6ded17c7 in ?? ()
#8  0x0000555d6ded242e in PortalRun ()
#9  0x0000555d6dece337 in ?? ()
#10 0x0000555d6decfdf0 in PostgresMain ()
#11 0x0000555d6de5ac6a in ?? ()
#12 0x0000555d6de5bb91 in PostmasterMain ()
#13 0x0000555d6dbe4258 in main ()

**Comment by pykello** [comment]
@fjalvingh which version of postgresql are you using?

**Comment by fjalvingh** [comment]
Hi Hadi, thanks for your interest.

I've been using it on Ubuntu, 12.4-0ubuntu0.20.04.1
